<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>True</ManagePackageVersionsCentrally>
    <PackageProjectUrl>https://github.com/webmaster442/csproj</PackageProjectUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/webmaster442/csproj</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>project;csharp;modify;bulk;command;cli;tool</PackageTags>
    <PackAsTool>True</PackAsTool>
    <Version>2.0.0.0</Version>
    <Description>Csproj is a tool that allows bulk modification of .csproj files. It provides a simple command-line interface to perform various operations on multiple .csproj files at once. It supports both sln and slnx formats.
</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <ToolCommandName>csproj</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CsProj.Tests" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>